### ISSUE TITLE
Using uploader in an action

### ISSUE THREAD

**Issue by peyterkim** [trick17media/t17-ember-upload#14]
If I'm trying to call an action in my controller on the upload, how would that look like?
```file_upload: function(){  var self = this; Ember.$.ajax({ **define uploadUrl and requestHeaders here** });}```

**Comment by rafaeliga** [comment]
hi @peyterkim, Im trying to do the same thing...did you get anything on that?

**Comment by sgasser** [comment]
Hi, your can use the actions of the mixin for uploading:
[uploadFile](https://github.com/trick17media/t17-ember-upload/blob/master/lib/t17-ember-upload/upload-mixin.js#L34) or [uploadAll](https://github.com/trick17media/t17-ember-upload/blob/master/lib/t17-ember-upload/upload-mixin.js#L81)

**Comment by peyterkim** [comment]
Hey @rafaeliga, I ended up using a component for my upload.

**Comment by rafaeliga** [comment]
alright @peyterkim, I got it working, I created a listener when the upload is done on my controller:

hasCompletedFile: function() {
    var controller = this;

    this.get('files').forEach(function(file) {
      var url = file.get('responseData.url');
      // set the url on my model
    });

    if (!Ember.isEmpty(this.get('model.url'))) {
      // save my model
    }
  }.observes('files.@each.didUpload'),

Im not sure if this is the best approach, but its wokirng for me

cc: @sgasser

**Comment by peyterkim** [comment]
@rafaeliga the only thing is, how would it handle large files? If large files aren't a use case in your situation I guess your solution will be fine.

**Comment by rafaeliga** [comment]
@peyterkim yeah...Im not handling this right now

**Comment by sgasser** [comment]
@rafaeliga your solution will be fine.
