### ISSUE TITLE
Ember.Deferred is deprecated warning.

### ISSUE THREAD

**Issue by vsymguysung** [trick17media/t17-ember-upload#16]
I am getting a warning saying "DEPRECATION: Usage of Ember.Deferred is deprecated."
Thanks.

**Comment by vsymguysung** [comment]
I found the solution myself. 
In ember 1.7, ```Ember.DeferredMixin``` and ```Ember.Deferred``` have been deprecated in favor of using ```RSVP.Promise```.

In fileObject.js file, Replace the following line 
```-            this.set('uploadPromise', Ember.Deferred.create());```
with this line.
```+            this.set('uploadPromise', Ember.RSVP.defer());```

Thanks.

**Comment by sgasser** [comment]
Fixed with PR #17
